-- Password=test
INSERT INTO APP_USERS(EMAIL, USER_NAME, PASSWORD) VALUES('abc@test.com', 'ABC', '$2a$10$u1iNPfAXHOL2ZLQhljq/mOISwUnVtJOPY5O8AVyLwHJNmmeqxBUPy');
INSERT INTO APP_USERS(EMAIL, USER_NAME, PASSWORD) VALUES('xyz@test.com', 'XYZ', '$2a$10$u1iNPfAXHOL2ZLQhljq/mOISwUnVtJOPY5O8AVyLwHJNmmeqxBUPy');